//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace PriceChecker.wrefProjectService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProjectServiceSoap", Namespace="http://www.uwm.edu/rtgreuel")]
    public partial class ProjectService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback addItemToDatabaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeItemFromDatabaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback getASINOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCurrentPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getItemDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLargeImageURLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProjectService() {
            this.Url = global::PriceChecker.Properties.Settings.Default.PriceChecker_wrefProjectService_ProjectService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckAliveCompletedEventHandler CheckAliveCompleted;
        
        /// <remarks/>
        public event addItemToDatabaseCompletedEventHandler addItemToDatabaseCompleted;
        
        /// <remarks/>
        public event removeItemFromDatabaseCompletedEventHandler removeItemFromDatabaseCompleted;
        
        /// <remarks/>
        public event getASINCompletedEventHandler getASINCompleted;
        
        /// <remarks/>
        public event getCurrentPriceCompletedEventHandler getCurrentPriceCompleted;
        
        /// <remarks/>
        public event getItemDescriptionCompletedEventHandler getItemDescriptionCompleted;
        
        /// <remarks/>
        public event getLargeImageURLCompletedEventHandler getLargeImageURLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/CheckAlive", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckAlive() {
            object[] results = this.Invoke("CheckAlive", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckAliveAsync() {
            this.CheckAliveAsync(null);
        }
        
        /// <remarks/>
        public void CheckAliveAsync(object userState) {
            if ((this.CheckAliveOperationCompleted == null)) {
                this.CheckAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAliveOperationCompleted);
            }
            this.InvokeAsync("CheckAlive", new object[0], this.CheckAliveOperationCompleted, userState);
        }
        
        private void OnCheckAliveOperationCompleted(object arg) {
            if ((this.CheckAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckAliveCompleted(this, new CheckAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/addItemToDatabase", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addItemToDatabase(string asin) {
            object[] results = this.Invoke("addItemToDatabase", new object[] {
                        asin});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addItemToDatabaseAsync(string asin) {
            this.addItemToDatabaseAsync(asin, null);
        }
        
        /// <remarks/>
        public void addItemToDatabaseAsync(string asin, object userState) {
            if ((this.addItemToDatabaseOperationCompleted == null)) {
                this.addItemToDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddItemToDatabaseOperationCompleted);
            }
            this.InvokeAsync("addItemToDatabase", new object[] {
                        asin}, this.addItemToDatabaseOperationCompleted, userState);
        }
        
        private void OnaddItemToDatabaseOperationCompleted(object arg) {
            if ((this.addItemToDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addItemToDatabaseCompleted(this, new addItemToDatabaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/removeItemFromDatabase", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool removeItemFromDatabase(string imageURL) {
            object[] results = this.Invoke("removeItemFromDatabase", new object[] {
                        imageURL});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void removeItemFromDatabaseAsync(string imageURL) {
            this.removeItemFromDatabaseAsync(imageURL, null);
        }
        
        /// <remarks/>
        public void removeItemFromDatabaseAsync(string imageURL, object userState) {
            if ((this.removeItemFromDatabaseOperationCompleted == null)) {
                this.removeItemFromDatabaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveItemFromDatabaseOperationCompleted);
            }
            this.InvokeAsync("removeItemFromDatabase", new object[] {
                        imageURL}, this.removeItemFromDatabaseOperationCompleted, userState);
        }
        
        private void OnremoveItemFromDatabaseOperationCompleted(object arg) {
            if ((this.removeItemFromDatabaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeItemFromDatabaseCompleted(this, new removeItemFromDatabaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/getASIN", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getASIN(string imageURL) {
            object[] results = this.Invoke("getASIN", new object[] {
                        imageURL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getASINAsync(string imageURL) {
            this.getASINAsync(imageURL, null);
        }
        
        /// <remarks/>
        public void getASINAsync(string imageURL, object userState) {
            if ((this.getASINOperationCompleted == null)) {
                this.getASINOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetASINOperationCompleted);
            }
            this.InvokeAsync("getASIN", new object[] {
                        imageURL}, this.getASINOperationCompleted, userState);
        }
        
        private void OngetASINOperationCompleted(object arg) {
            if ((this.getASINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getASINCompleted(this, new getASINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/getCurrentPrice", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCurrentPrice(string itemID) {
            object[] results = this.Invoke("getCurrentPrice", new object[] {
                        itemID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCurrentPriceAsync(string itemID) {
            this.getCurrentPriceAsync(itemID, null);
        }
        
        /// <remarks/>
        public void getCurrentPriceAsync(string itemID, object userState) {
            if ((this.getCurrentPriceOperationCompleted == null)) {
                this.getCurrentPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCurrentPriceOperationCompleted);
            }
            this.InvokeAsync("getCurrentPrice", new object[] {
                        itemID}, this.getCurrentPriceOperationCompleted, userState);
        }
        
        private void OngetCurrentPriceOperationCompleted(object arg) {
            if ((this.getCurrentPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCurrentPriceCompleted(this, new getCurrentPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/getItemDescription", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getItemDescription(string asin) {
            object[] results = this.Invoke("getItemDescription", new object[] {
                        asin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getItemDescriptionAsync(string asin) {
            this.getItemDescriptionAsync(asin, null);
        }
        
        /// <remarks/>
        public void getItemDescriptionAsync(string asin, object userState) {
            if ((this.getItemDescriptionOperationCompleted == null)) {
                this.getItemDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetItemDescriptionOperationCompleted);
            }
            this.InvokeAsync("getItemDescription", new object[] {
                        asin}, this.getItemDescriptionOperationCompleted, userState);
        }
        
        private void OngetItemDescriptionOperationCompleted(object arg) {
            if ((this.getItemDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getItemDescriptionCompleted(this, new getItemDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.uwm.edu/rtgreuel/getLargeImageURL", RequestNamespace="http://www.uwm.edu/rtgreuel", ResponseNamespace="http://www.uwm.edu/rtgreuel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLargeImageURL(string asin) {
            object[] results = this.Invoke("getLargeImageURL", new object[] {
                        asin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLargeImageURLAsync(string asin) {
            this.getLargeImageURLAsync(asin, null);
        }
        
        /// <remarks/>
        public void getLargeImageURLAsync(string asin, object userState) {
            if ((this.getLargeImageURLOperationCompleted == null)) {
                this.getLargeImageURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLargeImageURLOperationCompleted);
            }
            this.InvokeAsync("getLargeImageURL", new object[] {
                        asin}, this.getLargeImageURLOperationCompleted, userState);
        }
        
        private void OngetLargeImageURLOperationCompleted(object arg) {
            if ((this.getLargeImageURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLargeImageURLCompleted(this, new getLargeImageURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckAliveCompletedEventHandler(object sender, CheckAliveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addItemToDatabaseCompletedEventHandler(object sender, addItemToDatabaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addItemToDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addItemToDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void removeItemFromDatabaseCompletedEventHandler(object sender, removeItemFromDatabaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeItemFromDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeItemFromDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getASINCompletedEventHandler(object sender, getASINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getASINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getASINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCurrentPriceCompletedEventHandler(object sender, getCurrentPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCurrentPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCurrentPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getItemDescriptionCompletedEventHandler(object sender, getItemDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getItemDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getItemDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLargeImageURLCompletedEventHandler(object sender, getLargeImageURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLargeImageURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLargeImageURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591